Added custom base32 implementation as fallback in case the base32 binary is missing

diff --git a/otp b/otp
--- a/otp
+++ b/otp
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env bash
 
 # https://tools.ietf.org/html/rfc6238
 
@@ -11,7 +11,9 @@ function otp() {
     OTP_PERIOD="${OTP_PERIOD:-30}"
     OTP_ALGORITHM="${OTP_ALGORITHM:-SHA1}"
     OTP_SECRET_FILE="${OTP_SECRET_FILE:?Missing param}"
+    OTP_BASE32="${OTP_BASE32:-base32}"
 
+    # This is to avoid leaking the secret when running "bash -x".
     read -r secret < "${OTP_SECRET_FILE}"
     read -r secret <<<"${secret/otpauth*secret=/}"
     read -r secret <<<"${secret/&*/}"
@@ -19,9 +21,9 @@ function otp() {
     {
         # INTERVAL
         interval="$((${OTP_EPOCH} / ${OTP_PERIOD}))"
-        # integer to hex
+        # Integer to hex.
         printf -v hex "%016X" "${interval}"
-        # hex to binary
+        # Hex to binary.
         for ((i=0; i< "${#hex}"; i+=2))
         do
             echo -ne "\x${hex:i:2}"
@@ -29,7 +31,7 @@ function otp() {
     } | {
         # DIGEST
         # The digest is a 160-bit hexadecimal number string from interval.
-        openssl dgst -"${OTP_ALGORITHM}" -hmac "$(base32 -d <<<"${secret}")" | {
+        openssl dgst -"${OTP_ALGORITHM}" -hmac "$("${OTP_BASE32}" -d <<<"${secret}")" | {
             read digest
             echo "${digest/* /}"
         }
@@ -48,6 +50,21 @@ function otp() {
 # Return if the script was sourced
 return 0 2> /dev/null || true
 
+set -euo pipefail
+
+function base32_py() {
+    python3 -c "import base64, sys; sys.stdout.buffer.write(base64.b32decode(sys.stdin.read().strip()))"
+}
+
+# base32: Standard linux or macOS with coreutils.
+# base32_py: macOS without coreutils.
+function which_base32() {
+    command -v base32 \
+        || { command -v python3 > /dev/null && command -v base32_py; } \
+        || { echo "base32: command not found" >&2 && return 1; }
+}
+
+OTP_BASE32="${OTP_BASE32:-$(which_base32)}"
 OTP_SECRET_FILE="${OTP_SECRET_FILE:-/dev/stdin}"
 
 otp
